### PR TITLE
Chinese language, fixes and minor updates

### PR DESCRIPTION
**Pull request by uuidev**
# What was done

* Add Chinese language
* Arrange languages in README.md in alphabetical order
* Add one line between header & name in LICENSE in every file
* Delete header file (there is no need for it)
* Fix showing emojis in the arrow (check details)
* Remove UIKit from a non-UI service

# Implementation details

There was a bug when scrolling, in the arrow to source view we can see emojis

Bug

The version was updated to `3.0.8`

### CODE REVIEW

**Comment by uuidev** [comment]
Thanks again for your help with syncing my fork

**Comment by htmlprogrammist** [comment]
Please, change target branch from `main` to `develop`. There are some updates, it would be much easier for me

**Comment by htmlprogrammist** [comment]
It's my pleasure. Thank you again for contributing @uuidev!

**Review by htmlprogrammist — COMMENTED** [review]
Everything is fine. No need for further updates

**Pull request merged**
